# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: job1
    steps:
    - bash: echo first build function !!

  - job: job2
    steps:
    - bash: echo second build function !!


- stage: devenvironment
  dependsOn: build
  jobs:
  - job: devjob1
    steps:
    - bash: echo dev environment

  - job: devjob2
    steps:
    - bash: echo job2 dev environment

- stage: QAenvironment
  dependsOn: build
  jobs:
  - job: QAjob
    steps: 
    - bash : echo QA environment

- stage: prodenvironment
  dependsOn: 
  - devenvironment
  - QAenvironment
  jobs:
  - job: prodenvironment
    steps:
    - bash : echo prod environment

